### PR TITLE
Add initial models

### PR DESCRIPTION
**Pull request by apodiptych**
- [x] Move all core models into a separate `wobbly` app
- [x] Move views, serializers etc. into a separate `apiv1` app
- [x] Separate production and development settings

The last point is such that we can use SQLite for development. This is quicker to get up and running and not using docker for dev means that you get live reloading of views.

### CODE REVIEW

**Comment by apodiptych** [comment]
hey @nam20485, it looks like you've already written some models. i think data modeling is something we should decide on collectively; i suggest on this PR. in general, i think we should try to avoid committing directly to `develop` without a review -- both for cleaner commit logs (squashed branches) and for the convocational aspect :)

**Comment by nam20485** [comment]
The changes in this PR are no good. The initials setup for the apps is not useable. You have two different apps, I don't know why. Plus the migrations are no good. And it uses sqlite for the development. We want to use a postgres setup that matches our production setup. 

If you want to re-do the models, I would just use what is in development and throw away the contents of model.py. There is a bunch of change we want and everything set up super nice as far as the app goes.

**Comment by apodiptych** [comment]
i'm sorry, i think it will be hard to constructively move forward like this -- i feel that your tone is quite antagonistic and i don't feel that you leave much room for differing opinions. for instance, i would have appreciated a discussion on some of the changes here rather than hearing that it is "no good". i'd like to see the backend (and the entire project) feel like a collective project with room for discussion.

perhaps i could have been clearer, but this PR -- like all PRs, in my opinion -- is a set of suggested changes to be reviewed together as a team.

**Comment by nam20485** [comment]
> i'm sorry, i think it will be hard to constructively move forward like this -- i feel that your tone is quite antagonistic and i don't feel that you leave much room for differing opinions. for instance, i would have appreciated a discussion on some of the changes here rather than hearing that it is "no good".

I'm not being antagonistic. I apologize- after reading my comment I can see that it was a bit hasty and I sounded short, but I didn't intend to be dismissive. "No good" was not a characterization of the quality of the code contained in your proposed commits. I was referring to the fact that the structure you had set up would not operate or support continuing forward with it (as I mentioned in my comment about the segmentation into two separate apps during your initial creation). It contains configuration that the group has discussed and decided we would not go forward with (sqlite for the DB and no Docker for the local development version of the setup, which I also explained). It also fails the existing unit tests and won't deploy into our existing deployment structure. I believe also that the migrations would not be backwards compatible.

The structure we have created in the progress we have made since you initially created this pull request is not compatible with the changes in this PR, I think it literally wouldn't merge in to our current development branch. So using these changes would mean throwing away the progress we have made during the last two months of work. Also one other thing I don't understand is why you embedded the version number of the API into the app name ("apiv1").

> i'd like to see the backend (and the entire project) feel like a collective project with room for discussion.

I agree, but I think a more productive and practical course of action than throwing away the progress we have made during the last two months by deciding to review and go forward by re-implementing what we already have using this PR, would be maybe collaboratively going over and explaining what we have working currently in the development branch, or something similar to that, which would allow you and any interested parties to benefit from the same learning process and gain understanding of Django in general, and our implementation/structure specifically. Maybe we could review what he have already working in the development branch and discuss any proposed changes you come up with, and answer questions you have about the design/implementation.

(I also do like the change where you split out the settings.py into a development and production version and import them)

> perhaps i could have been clearer, but this PR -- like all PRs, in my opinion -- is a set of suggested changes to be reviewed together as a team.

I fully agree. 

I have invested a great deal of effort and time over the last two months into developing the working backend code that currently exists in the development branch. It functions and works well, and also represents a lot of research I have had to perform to find solutions to several difficult problems encountered getting the functionality we needed implemented.

I have kept everyone informed and apprised of my progress as I have finished it during the last several standup meetings and in discord chats, and received approval of what I was doing as I completed it, including during the last meeting when we agreed that I would make an initial attempt at implementing the data model using the graphql data model schema definition we previously had. 

So at his point and I am surprised and confused that you would propose throwing it away and starting from scratch with the contents of this PR. I don't think its practical or productive and am opposed to taking this approach now. Not only because what we have now is working well, representing a mostly-finished backend service prototype which is ready for frontend development, but also because I have invested a lot of time and effort into getting it to this point.

I mentioned in my comment above that we could redo the data model in the current development branch implementation and that is what I propose we should do. Unless I am misunderstanding, that colloborative creation of the datamodel is your goal as well. 

>in general, i think we should try to avoid committing directly to develop without a review -- both for cleaner commit logs (squashed branches) and for the convocational aspect :)

I agree that we should implement required review approval for PR instead overriding and force-pushing them. I actually have this required in the backend repo, but was informed early on that having PR checks like unit tests passing and reviewer approval was an impediment to new developers being able to contribute code quickly so they were asked to be removed, and I believe were removed in the frontend repo. During the last couple months, you, I, and Marc have been committing at will to the repos frequently and it has never been a problem. So I fully agree that we should be avoiding committing directly, and would like to start requiring a review approval policy now. Maybe I am misunderstanding, but it seems arbitrary to state that we should already have been avoiding it.

**Comment by apodiptych** [comment]
thank you for the apology -- i appreciate it. i'm happy to explain the reasoning behind the changes i made:

* first of all, splitting up `wobbly` and `backend` into separate apps was an error on my part -- but easily remedied :)
* using a separate `apiv1` app is to separate the view layer from the model layer. this, as well as the `v1` suffix, is to make a major version bump of the API possible in the future. in that case, we'd probably want to run both APIs v1 and v2 next to each other to give clients time to upgrade. this is a suggested best practice from the two scoops of django book.
* i used SQLite rather than docker because i was frustrated by the lack of live reloading and the difficulty of running `manage.py` commands for development. i think this should be possible still using docker, though (using a volume in docker-compose rather than `COPY`, maybe?). i'll look into it.

and a few other responses:

> I believe also that the migrations would not be backwards compatible.

yes, that's true. but we don't have any data on the servers so this seems easily resolved? and the reason they won't be backwards compatible is because you created the models without a PR. i didn't have a chance to make them backwards compatible.

> I think it literally wouldn't merge in to our current development branch

again, because `develop` changed significantly from the time i branched (but without PRs). 

> So using these changes would mean throwing away the progress we have made during the last two months of work.

i certainly wouldn't want to throw away that progress! i appreciate the work you've put into the backend and this project in general. i don't think these changes would mean throwing that away, especially since i branched off from a relatively recent commit.

> we agreed that I would make an initial attempt at implementing the data model using the graphql data model schema definition we previously had

the source of my opposition here is that this data model ended up in our main branch without a collective review.

> During the last couple months, you, I, and Marc have been committing at will to the repos frequently and it has never been a problem

i haven't been committing or merging anything to `develop` without a PR -- that's the model i'd like to see, but i think we agree on this :) i'm strongly in favor of disabling direct commits to the `develop`, `staging`, and `production` branches and only allowing merge commits (ideally squashed IMO).

in the interest of moving forward, i'll close this PR and create a number of new ones for the specific changes i suggest and we can discuss them individually there. i agree re: taking the existing `models.py` and modifying it as needed. right now, i'll open PRs for
* enabling live-reload and easy access to `manage.py` in docker for a better dev experience
* separating the model and view layers into separate apps
* separating development and production settings in different files

i reacted strongly because i felt that my contributions were dismissed not based on their merit, but because they did not match the changes that you made to the main branch. i respect the work you've done here and i hope we can reconcile and work on this project together.

**Pull request closed without merging**
